language: node_js
node_js:
  - "5.12"
env:
  - CXX=g++-4.8
before_script:
  - npm update -g npm
  - npm install -g dredd@stable
script:
  - dredd odin.apib http://137.135.84.77 --hookfiles=dredd.js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8