language: node_js
node_js:
  - '5.12'
env:
  - CXX=g++-4.8
before_script:
  - npm update -g npm
  - npm install -g dredd@unstable
script:
  - dredd odin.apib http://54.175.155.181:3000 --hookfiles=dredd.js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
