language: node_js
node_js:
  - "5.12"
env:
  - CXX=g++-4.8
  global:
    - PGPORT=5432
    - PGHOST=localhost
    - DATABASE_URL=postgres://localhost:5432/odin
sudo: required
before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -c 'CREATE DATABASE odin;' -U postgres
  - psql -c "ALTER USER postgres with password 'postgres';" -U postgres
  - mkdir /tmp/odin
  - mkdir /tmp/odin/sWRhpRk
  - mkdir /tmp/odin/sWRhpRm
  - mkdir /tmp/odin/sWRhpRn
  - mkdir /tmp/odin/sWRhpRl
  - mkdir /tmp/odin/sWRhpRo
  - sudo chmod 777 -R /tmp/odin
  - npm update -g npm
  - npm install -g dredd@stable
  - npm install -g node-gyp
  - cd /home/travis/build/gcba-odin/odin/node_modules/detect-character-encoding
  - node-gyp rebuild
  - cd /home/travis/build/gcba-odin/odin
script:
  - make test
services:
  - mongodb
  - postgresql
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    - ubuntu-toolchain-r-test
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
    - g++-4.8
  postgresql: 9.5
