language: node_js
node_js:
  - '5.12'
env:
  - CXX=g++-4.8
sudo: required
before_install:
  - psql -c 'create database odin;' -U postgres
  - psql -c "ALTER USER postgres with password 'postgres';" -U postgres
  - mkdir /tmp/odin
  - mkdir /tmp/odin/sWRhpRk
  - mkdir /tmp/odin/sWRhpRm
  - mkdir /tmp/odin/sWRhpRn
  - mkdir /tmp/odin/sWRhpRl
  - mkdir /tmp/odin/sWRhpRo
  - sudo chmod 777 -R /tmp/odin
  - npm update -g npm
  - npm install -g dredd@stable
  - npm install -g node-gyp
  - cd /home/travis/build/gcba-odin/odin/node_modules/detect-character-encoding
  - node-gyp rebuild
  - cd /home/travis/build/gcba-odin/odin
script:
    - make test
services:
  - mongodb
addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
