reporter: apiary
custom:
  apiaryApiKey: 065280ba8b01fdbcbe986cd4602bb01f
  apiaryApiName: odin2
dry-run: null
hookfiles: dredd.js
language: nodejs
blueprint: odin.apib
endpoint: 'http://127.0.0.1:3000'
sandbox: false
server: npm start
server-wait: 7
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: silly
timestamp: false
silent: false
path: []
hooks-worker-timeout: 200
hooks-worker-connect-timeout: 200
hooks-worker-connect-retry: 200
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 200
hooks-worker-term-retry: 200
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321

